media:
  input: src/content/images
  output: ../images
  extensions: [ png, webp, jpeg, jpg, gif ]
content:
  - name: projects
    label: Projects
    type: collection
    filename: '{primary}.md'
    path: 'src/content/projects'
    view:
      fields: [ title, website-link, showcased, icon, order, cover, card-subheadline, category, keywords, project-subheadline-1, project-text-1, square-image, gallery, project-subheadline-2, project-text-2, quote ]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: website-link
        label: Company website link
        type: string
      - name: showcased
        label: Showcased on landing page
        type: boolean
        default: false
        required: true
      - name: icon
        label: Project icon or logo
        description: This shows up on the landing page, if the project is showcased. Use transparent images with white colors. Resolution should be 150x60, the logo should fit in this.
        type: image
      - name: order
        label: Project Order on landing page
        type: number
        description: Only works if it is showcased on the landing page. Leave it empty if it isn't showcased.
        options:
          max: 4
      - name: cover
        label: Cover Image
        description: This shows up on the landing page, in the project card, and in the cover image. It is 16:9 ratio, except on larger desktop views, where it is 21:9 ratio
        type: image
        required: true
      - name: card-subheadline
        label: Card Subheadline
        type: text
        options:
          maxlength: 35
      - name: category
        label: Category
        type: select
        required: true
        options:
          multiple: true
          values: [ Performance, Creative, Digital, Production ]
      - name: keywords
        label: Keywords
        type: select
        options:
          creatable: true
          multiple: true
      - name: project-subheadline-1
        label: First subheadline
        type: text
        required: true
        options:
          maxlength: 70
      - name: project-text-1
        label: First main text
        type: text
        required: true
      - name: square-image
        label: Square image (1:1 ratio)
        type: image
        required: true
      - name: gallery
        label: Image Gallery
        type: image
        options:
          multiple:
            max: 6
      - name: project-subheadline-2
        label: Second subheadline
        type: text
        options:
          maxlength: 70
      - name: project-text-2
        label: Second main text
        description: Enters will be separated into columns in desktop view.
        type: text
      - name: quote
        label: Review
        type: object
        fields:
          - name: author
            label: Author
            type: string
            options:
              maxlength: 50
          - name: quote-text
            label: Review Text
            type: text
          - name: quote-text-landing
            label: Review Text Shown In Landing Page
            type: text
          - name: quote-showcased
            label: Showcased on landing page
            type: boolean
            default: false
          - name: order
            label: Review Order on landing page
            type: number
            description: Only works if it is showcased on the landing page. Leave it empty if it isn't showcased.
            options:
              max: 7
  - name: team
    label: Team
    type: collection
    filename: '{primary}.md'
    path: 'src/content/team'
    view:
      fields: [ name, picture, role ]
    fields:
      - name: name
        label: Name
        type: string
        required: true
      - name: picture
        label: Picture
        description: The picture of the person should be 1:1 aspect ratio, like a box. The bottom part of the picture is designed to be cut off.
        type: image
        required: true
      - name: role
        label: Job role
        type: string
        required: true
      - name: order
        label: Order of the person, starting from left to right.
        type: number
        required: true
  - name: career
    label: Career
    type: collection
    filename: '{primary}.md'
    path: 'src/content/career'
    view:
      fields: [ name, sections ]
    fields:
      - name: name
        label: Job Title
        type: string
        required: true
      - name: sections
        label: Page Sections
        type: block
        list: true # Often used with type: block to allow multiple sections
        blockKey: type # Optional: customize the key used to store the block name, defaults to `_block`
        blocks:
          # Each item defines a possible block structure the user can select.
          # These typically use 'component' or define 'fields' directly.
          - name: left
            label: A new block
            fields:
              - name: left
                label: Left side short text
                type: string
              - name: right
                label: Right side block, can be anything
                type: rich-text