media:
  input: src/content/projects/images
  output: ./images
  extensions: [ png, webp, jpeg, jpg, gif ]
content:
  - name: projects
    label: Projects
    type: collection
    filename: '{primary}.md'
    path: 'src/content/projects'
    view:
      fields: [ title, showcased, cover, card-subheadline, category, keywords, project-subheadline-1, project-text-1, square-image, gallery, project-subheadline-2, project-text-2, quote ]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: showcased
        label: Showcased on landing page
        type: boolean
        default: false
        required: true
      - name: cover
        label: Cover Image
        type: image
        required: true
      - name: card-subheadline
        label: Card Subheadline
        type: text
        options:
          maxlength: 140
      - name: category
        label: Category
        type: select
        required: true
        options:
          values: [ Performance, Creative, Digital, Production ]
      - name: keywords
        label: Keywords
        type: select
        options:
          creatable: true
          multiple: true
      - name: project-subheadline-1
        label: First subheadline
        type: text
        required: true
        options:
          maxlength: 140
      - name: project-text-1
        label: First main text
        type: text
        required: true
      - name: square-image
        label: Square image (1:1 ratio)
        type: image
        required: true
      - name: gallery
        label: Image Gallery
        type: image
        options:
          multiple:
            max: 6
      - name: project-subheadline-2
        label: Second subheadline
        type: text
        options:
          maxlength: 140
      - name: project-text-2
        label: Second main text
        type: text
      - name: quote
        label: Quote
        type: object
        fields:
          - name: author
            label: Author
            type: string
            options:
              maxlength: 100
          - name: quote-text
            label: Quote Text
            type: text
  - name: site
    label: Site settings
    path: src/_data/site.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)